### Create a route for the UCT service Properties
curl -i -X POST \
--url http://localhost:8001/services/uct/routes \
--data 'name=uct-properties' \
--data 'paths=/Properties' \
--data 'strip_path=false'