### Add rate limiting plugin to the UCT service

curl -X POST http://localhost:8001/services/uct/plugins \
  --data "name=rate-limiting" \
  --data "config.minute=5" \
  --data "config.policy=local"


# curl -i -X POST http://localhost:8001/plugins \
#   --data name=rate-limiting \
#   --data config.minute=5 \
#   --data config.policy=local
