### Add rate limiting plugin to the UCT service
curl -i -X POST \
--url http://localhost:8001/services/uct/plugins/ \
--data 'name=rate-limiting' \
--data 'config.minute=10' \ 
--data 'config.hour=20' \
--data 'config.policy=local' 