services:
  db-migration:
    build: .
    environment:
      PGUSER: ${KONG_PG_USER:-iam}
    volumes:
      - 'pgdata:/var/lib/postgresql/9.6/data'
      - 'pgdata17:/var/lib/postgresql/17/data'
    stdin_open: true
volumes:
  pgdata:
  pgdata17:
